name: deploy_pages

on:
  workflow_call:
    secrets:
      KEY:
        required: true
    inputs:
      REPOSITORY:
        required: true
        type: string
      COMMITTER_NAME:
        required: true
        type: string
      COMMITTER_EMAIL:
        required: true
        type: string
      CNAME:
        required: true
        type: string
      DOTENV:
        required: true
        type: string

jobs:
  deploy_pages:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Remove previous build output and .env file
        run: rm -rf dist .env
      - name: Create environment file
        run: echo "${{ inputs.DOTENV }}" > .env
      - name: Build the website
        run: pnpm run build
      - name: Add CNAME
        run: echo "${{ inputs.CNAME }}" >> dist/CNAME
      - name: Push build
        run: |
          rm -rf ssh.key
          echo "${{ secrets.KEY }}" >> ssh.key
          cd dist
          git init
          git remote add origin ${{ inputs.REPOSITORY }}
          git config --global user.email "${{ inputs.COMMITTER_NAME }}"
          git config --global user.name "${{ inputs.COMMITTER_EMAIL }}"
          git config --add --local core.sshCommand 'ssh -i ../ssh.key'
          git checkout -b main
          git add .
          git commit -m "Automatic build & release"
          git push --force -u origin main
          git config --unsert --local core.sshCommand
          rm -rf ssh.key
