name: standard_ci

on: [pull_request, push]

jobs:
  call-workflow-tests:
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
      pull-requests: write

  call-workflow-supabase-deploy-production:
    uses: ./.github/workflows/supabase_migrations.yml
    needs: [call-workflow-tests]
    if: ${{ vars.DEPLOY_SUPABASE_PRODUCTION == 'y' && github.repository == 'ErrorsParty/website' && github.ref == 'refs/heads/prod' }}
    permissions:
      contents: write
      pull-requests: write
    with:
      PROJECT_ID: ${{ vars.SUPABASE_PRODUCTION_PROJECT_ID }}
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PRODUCTION_ACCESS_TOKEN }}
      SUPABASE_DATABASE_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DATABASE_PASSWORD }}

  call-workflow-supabase-deploy-staging:
    uses: ./.github/workflows/supabase_migrations.yml
    needs: [call-workflow-tests]
    if: ${{ vars.DEPLOY_SUPABASE_STAGING == 'y' && github.repository == 'ErrorsParty/website' && github.ref == 'refs/heads/staging' }}
    permissions:
      contents: write
      pull-requests: write
    with:
      PROJECT_ID: ${{ vars.SUPABASE_STAGING_PROJECT_ID }}
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_STAGING_ACCESS_TOKEN }}
      SUPABASE_DATABASE_PASSWORD: ${{ secrets.SUPABASE_STAGING_DATABASE_PASSWORD }}
