name: standard_ci

on: [pull_request, push]

jobs:
  call-workflow-tests:
    uses: ./.github/workflows/tests.yml

  call-workflow-supabase-deploy-production:
    uses: ./.github/workflows/supabase_migrations.yml
    needs: [call-workflow-tests]
    if: ${{ vars.DEPLOY_SUPABASE_PRODUCTION == 'y' && github.repository == vars.SELF_REPOSITORY && github.ref == 'refs/heads/prod' }}
    with:
      PROJECT_ID: ${{ vars.SUPABASE_PRODUCTION_PROJECT_ID }}
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_PRODUCTION_ACCESS_TOKEN }}
      SUPABASE_DATABASE_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DATABASE_PASSWORD }}

  call-workflow-supabase-deploy-staging:
    uses: ./.github/workflows/supabase_migrations.yml
    needs: [call-workflow-tests]
    if: ${{ vars.DEPLOY_SUPABASE_STAGING == 'y' && github.repository == vars.SELF_REPOSITORY && github.ref == 'refs/heads/staging' }}
    with:
      PROJECT_ID: ${{ vars.SUPABASE_STAGING_PROJECT_ID }}
    secrets:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_STAGING_ACCESS_TOKEN }}
      SUPABASE_DATABASE_PASSWORD: ${{ secrets.SUPABASE_STAGING_DATABASE_PASSWORD }}

  call-workflow-pages-deploy-staging:
    uses: ./.github/workflows/deploy_pages.yml
    needs: [call-workflow-tests]
    if: ${{ vars.DEPLOY_PAGES_STAGING == 'y' && github.repository == vars.SELF_REPOSITORY && github.ref == 'refs/heads/staging' }}
    with:
      REPOSITORY: ${{ vars.DEPLOY_PAGES_STAGING_REPOSITORY }}
      CNAME: ${{ vars.DEPLOY_PAGES_STAGING_CNAME }}
      DOTENV: ${{ vars.VITE_ENVIRONMENT_STAGING }}
      COMMITTER_NAME: ${{ VARS.DEPLOY_PAGES_STAGING_COMMITTER_NAME }}
      COMMITTER_EMAIL: ${{ VARS.DEPLOY_PAGES_STAGING_COMMITTER_EMAIL }}
    secrets:
      KEY: ${{ secrets.DEPLOY_PAGES_STAGING_KEY }}

  call-workflow-pages-deploy-production:
    uses: ./.github/workflows/deploy_pages.yml
    needs: [call-workflow-tests]
    if: ${{ vars.DEPLOY_PAGES_PRODUCTION == 'y' && github.repository == vars.SELF_REPOSITORY && github.ref == 'refs/heads/prod' }}
    with:
      REPOSITORY: ${{ vars.DEPLOY_PAGES_PRODUCTION_REPOSITORY }}
      CNAME: ${{ vars.DEPLOY_PAGES_PRODUCTION_CNAME }}
      DOTENV: ${{ vars.VITE_ENVIRONMENT_PRODUCTION }}
      COMMITTER_NAME: ${{ VARS.DEPLOY_PAGES_PRODUCTION_COMMITTER_NAME }}
      COMMITTER_EMAIL: ${{ VARS.DEPLOY_PAGES_PRODUCTION_COMMITTER_EMAIL }}
    secrets:
      KEY: ${{ secrets.DEPLOY_PAGES_PRODUCTION_KEY }}
