name: supabase_migrations

on:
  workflow_call:
    secrets:
      SUPABASE_ACCESS_TOKEN:
        required: true
      SUPABASE_DATABASE_PASSWORD:
        required: true
    inputs:
      PROJECT_ID:
        required: true
        type: string

jobs:
  deploy_supabase:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DATABASE_PASSWORD }}
      PROJECT_ID: ${{ inputs.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1

      - name: Link Supabase CLI to project
        run: supabase link --project-ref $PROJECT_ID

      - name: Push database migrations
        run: supabase db push
